version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: cd_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    volumes:
      - /home/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306

  spring-boot:
    image: chaimask/chaima:69
    container_name: cd_spring
    ports:
      - 8089:8089
    depends_on:
      - database
    restart: on-failure
